apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
  namespace: "2401072"
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP