apiVersion: v1
kind: Service
metadata:
  name: interviewhub-service
  labels:
    app: interviewhub
spec:
  type: NodePort
  selector:
    app: interviewhub
  ports:
    - protocol: TCP
      port: 3000          # service port
      targetPort: 3000    # container port
      nodePort: 31000     # browser: http://localhost:31000
